# run maven build first! then use docker-compose up to run docker-composer.yml
# remove image secrets_serverapp after changes before bringing it up again!
version: '3'
services:
  serverapp:
    build: .
    ports:
     - "5000:5000"
#    volumes:
#     - .:/code

#--mount source=myvol2,target=/app
#docker run --rm --mount source=myvol2,target=/app -w /app java:8 javac de\fehrprice\secrets\App.java

#power shell examples from local folder C:\dev\docker\secrets\secrets\src\main\java:
#docker run --rm -v ${PWD}:/data -w /data java:8 javac de/fehrprice/secrets/App.java
#docker run --rm -v ${PWD}:/data -w /data java:8 java de.fehrprice.secrets.App